Repository ava-labs/subnet-evm, pull requests merged in 2022-11, with the labels that each got.

#330 Block Acceptor from Flattening during Verification
  core/blockchain.go
  utils/metered_cache.go
Labels: bug

#329 Remove networks dir
  .github/workflows/json-lint.yml
  networks/README.md
  networks/mainnet/432204/README.md
  networks/mainnet/432204/contracts.json
  networks/mainnet/432204/genesis.json
  networks/mainnet/53935/README.md
  networks/mainnet/53935/contracts.json
  networks/mainnet/53935/genesis.json
  networks/mainnet/53935/upgrade.json
  networks/mainnet/73772/README.md
  networks/mainnet/73772/contracts.json
  networks/mainnet/73772/genesis.json
  networks/mainnet/73772/upgrade.json
  networks/testnet/11111/genesis.json
  networks/testnet/11111/upgrade.json
  networks/testnet/335/README.md
  networks/testnet/335/contracts.json
  networks/testnet/335/genesis.json
  networks/testnet/335/upgrade.json
  networks/testnet/432201/README.md
  networks/testnet/432201/contracts.json
  networks/testnet/432201/genesis.json
  networks/testnet/432201/upgrade.json
  networks/testnet/73773/README.md
  networks/testnet/73773/contracts.json
  networks/testnet/73773/genesis.json
  networks/testnet/73773/upgrade.json
  networks/testnet/808/README.md
  networks/testnet/808/contracts.json
  networks/testnet/808/genesis.json
Labels: blocked, cleanup

#336 Improve run script and fix small binding bug on precompile template
  accounts/abi/bind/bind.go
Labels: bug, precompile

#343 Improve Cache Performance
  core/blockchain.go
  core/state/trie_prefetcher.go
  trie/database.go
Labels: bug

#350 Update AvalancheGo compatibility in README
  README.md
Labels: documentation

#352 add prints to activating precompiles
  accounts/abi/bind/precompile_template.go
  params/precompile_config.go
  precompile/contract_deployer_allow_list.go
  precompile/contract_native_minter.go
  precompile/fee_config_manager.go
  precompile/stateful_precompile_config.go
  precompile/tx_allow_list.go
Labels: precompile

#353 Fix e2e tests for github workflow
  contract-examples/test/ExampleFeeManager.ts
  scripts/parser/go.mod
  scripts/parser/go.sum
  scripts/parser/main.go
  scripts/run.sh
  tests/e2e/e2e_test.go
Labels: bug

#344 [e2e cleanups 1] Fix e2e tests with ginkgo label selector, remove unused npx tests
  .github/workflows/lint-tests-release.yml
  .golangci.yml
  README.md
  cmd/simulator/main.go
  contract-examples/test/ExampleFeeManager.ts
  go.mod
  go.sum
  scripts/parser/go.mod
  scripts/parser/go.sum
  scripts/parser/main.go
  scripts/run.sh
  tests/e2e/e2e_test.go
  tests/e2e/ping/suites.go
  tests/e2e/runner/runner.go
  tests/e2e/solidity/suites.go
  tests/e2e/utils/command.go
  tests/e2e/utils/evm_client.go
  tests/e2e/utils/out.go
  tests/e2e/utils/params.go
  tests/e2e/utils/parser.go
Labels: ci

#357 Add accepted txs metrics
  core/blockchain.go
Labels: enhancement

#360 Add counter for verified transactions
  core/blockchain.go
Labels: enhancement, coreth-update

#260 Reward Manager precompile
  accounts/abi/bind/precompile_template.go
  consensus/consensus.go
  consensus/dummy/consensus.go
  contract-examples/README.md
  contract-examples/contracts/ExampleFeeManager.sol
  contract-examples/contracts/ExampleRewardManager.sol
  contract-examples/contracts/IAllowList.sol
  contract-examples/contracts/IRewardManager.sol
  contract-examples/scripts/deployExampleRewardManager.ts
  contract-examples/tasks.ts
  contract-examples/test/ExampleRewardManager.ts
  core/blockchain_reader.go
  core/chain_makers.go
  core/stateful_precompile_test.go
  miner/worker.go
  params/config.go
  params/precompile_config.go
  plugin/evm/block_verification.go
  plugin/evm/vm.go
  plugin/evm/vm_test.go
  precompile/config_test.go
  precompile/contract.go
  precompile/params.go
  precompile/reserved_range.go
  precompile/reward_manager.go
  tests/e2e/genesis/reward_manager.json
  tests/e2e/solidity/suites.go
  vmerrs/vmerrs.go
Labels: precompile

#370 Fix codeowners wildcard pattern
  .github/CODEOWNERS
Labels: bug

#374 nit: remove gotest.tools dependency
  go.mod
  go.sum
  precompile/utils_test.go
Labels: cleanup

#375 Update AddLog function signature to support usage from precompiles
  core/state/statedb.go
  core/state/statedb_test.go
  core/vm/instructions.go
  core/vm/interface.go
  precompile/contract.go
Labels: precompile

#373 Pack topics
  accounts/abi/abi.go
  accounts/abi/abi_test.go
  accounts/abi/topics.go
Labels: enhancement

#377 Migrate replay protection bypass for Nick's Method Signature txs
  core/types/transaction_signing_test.go
  eth/api_backend.go
  eth/api_backend_test.go
  eth/backend.go
  eth/ethconfig/config.go
  internal/ethapi/api.go
  internal/ethapi/backend.go
  plugin/evm/config.go
  plugin/evm/config_test.go
  plugin/evm/vm.go
Labels: coreth-update

#381 Plumbing snow.Context for precompiles
  cmd/simulator/go.mod
  cmd/simulator/go.sum
  core/stateful_precompile_test.go
  core/vm/evm.go
  params/config.go
  plugin/evm/vm.go
  precompile/contract.go
Labels: enhancement
