Repository ava-labs/subnet-evm, pull requests merged in 2022-10, with the labels that each got.

#286 Correct a link to doc site
  README.md
Labels: documentation

#293 Update avalanchego v1.9.0
  cmd/simulator/go.mod
  cmd/simulator/go.sum
  go.mod
  go.sum
  scripts/versions.sh
Labels: dependencies

#296 Update v0.4.0 compatibility with avalanchengo v1.9.0
  README.md
Labels: documentation

#305 DFK Chain testnet upgrade bytes to disable contract deployer allowlist
  networks/testnet/335/upgrade.json
Labels: subnet-upgrades

#306 Review nits for porting corethv0.10.1
  core/state/statedb.go
  eth/filters/api.go
  plugin/evm/vm.go
Labels: coreth-update

#310 Add cache config options for trie db and snapshot
  eth/backend.go
  eth/ethconfig/config.go
  plugin/evm/config.go
  plugin/evm/vm.go
Labels: enhancement, coreth-update

#311 Save cache periodically
  core/blockchain.go
  core/blockchain_test.go
  eth/backend.go
  eth/ethconfig/config.go
  plugin/evm/config.go
  trie/database.go
Labels: enhancement

#316 fixes flakes in TestArchiveBlockChainSnapsDisabled
  core/test_blockchain.go
Labels: test-fix

#319 Save cache periodically test
  cmd/simulator/go.mod
  cmd/simulator/go.sum
  core/blockchain.go
  core/blockchain_test.go
  go.mod
  go.sum
  plugin/evm/vm.go
Labels: enhancement, test-fix

#324 Bump avalanchego v1.9.1
  cmd/simulator/go.mod
  cmd/simulator/go.sum
  go.mod
  go.sum
  peer/network.go
  peer/network_test.go
  plugin/evm/client.go
  plugin/evm/syncervm_test.go
  plugin/evm/tx_gossiping_test.go
  plugin/evm/vm_test.go
  scripts/versions.sh
Labels: dependencies, coreth-update
