Repository ava-labs/subnet-evm, pull requests merged in 2022-08, with the labels that each got.

#211 CallDetailed
  internal/ethapi/api.go
Labels: enhancement

#210 ports commit locking from coreth
  core/blockchain.go
  core/chain_makers.go
  core/genesis.go
  core/state/database.go
  core/state/snapshot/generate_test.go
  core/state/state_object.go
  core/state/statedb.go
  core/state/statedb_test.go
  core/state_manager.go
  core/state_manager_test.go
  eth/state_accessor.go
  eth/tracers/api.go
  statesync/handlers/leafs_request_test.go
  tests/state_test_util.go
  trie/committer.go
  trie/database.go
  trie/database_test.go
  trie/iterator_test.go
  trie/secure_trie.go
  trie/secure_trie_test.go
  trie/sync_test.go
  trie/test_trie.go
  trie/trie.go
  trie/trie_test.go
Labels: bug

#231 add upgrade bytes for DFK Chain testnet
  networks/testnet/335/upgrade.json
Labels: subnet-upgrades

#222 Portal fantasy subnet info
  networks/README.md
  networks/testnet/808/README.md
  networks/testnet/808/contracts.json
  networks/testnet/808/genesis.json
Labels: subnet-upgrades

#239 Add DFK Chain mainnet upgrade bytes
  networks/mainnet/53935/upgrade.json
Labels: subnet-upgrades
