Repository ava-labs/subnet-evm, pull requests merged in 2022-12, with the labels that each got.

#384 Add CallFromPrecompile to PrecompileAccessibleState
  core/stateful_precompile_test.go
  core/vm/evm.go
  precompile/contract.go
Labels: enhancement

#402 Bump avalanchego to v1.9.4
  cmd/simulator/go.mod
  cmd/simulator/go.sum
  go.mod
  go.sum
  scripts/versions.sh
Labels: dependencies

#418 rework on panics in precompiles
  accounts/abi/bind/precompile_template.go
  core/genesis.go
  core/state_processor.go
  miner/worker.go
  params/precompile_config.go
  precompile/allow_list.go
  precompile/contract.go
  precompile/contract_deployer_allow_list.go
  precompile/contract_native_minter.go
  precompile/fee_config_manager.go
  precompile/reward_manager.go
  precompile/stateful_precompile_config.go
  precompile/tx_allow_list.go
  precompile/utils.go
Labels: enhancement, precompile, cleanup
