Repository ava-labs/subnet-evm, pull requests merged in 2023-05, with the labels that each got.

#565 Generate precompile tests
  accounts/abi/bind/bind.go
  accounts/abi/bind/precompilebind/precompile_bind.go
  accounts/abi/bind/precompilebind/precompile_bind_test.go
  accounts/abi/bind/precompilebind/precompile_config_test_template.go
  accounts/abi/bind/precompilebind/precompile_contract_template.go
  accounts/abi/bind/precompilebind/precompile_contract_test_template.go
  cmd/precompilegen/main.go
  params/precompile_config_test.go
  precompile/allowlist/test_allowlist_config.go
  precompile/contracts/deployerallowlist/config_test.go
  precompile/contracts/feemanager/config_test.go
  precompile/contracts/nativeminter/config_test.go
  precompile/contracts/rewardmanager/config_test.go
  precompile/contracts/txallowlist/config_test.go
  precompile/testutils/test_config.go
Labels: precompile

#641 rename state upgrade test
  params/state_upgrade_test.go
Labels: cleanup

#601 Migrate HardHat tests to DS-tests (Solidity tests)
  contract-examples/contracts/AllowList.sol
  contract-examples/contracts/ERC20NativeMinter.sol
  contract-examples/contracts/ExampleDeployerList.sol
  contract-examples/contracts/ExampleFeeManager.sol
  contract-examples/contracts/ExampleRewardManager.sol
  contract-examples/contracts/ExampleTxAllowList.sol
  contract-examples/contracts/test/AllowListTest.sol
  contract-examples/contracts/test/ERC20NativeMinterTest.sol
  contract-examples/contracts/test/ExampleDeployerListTest.sol
  contract-examples/contracts/test/ExampleFeeManagerTest.sol
  contract-examples/contracts/test/ExampleRewardManagerTest.sol
  contract-examples/contracts/test/ExampleTxAllowListTest.sol
  contract-examples/hardhat.config.ts
  contract-examples/test/contract_deployer_allow_list.ts
  contract-examples/test/contract_native_minter.ts
  contract-examples/test/fee_manager.ts
  contract-examples/test/reward_manager.ts
  contract-examples/test/tx_allow_list.ts
  tests/precompile/genesis/contract_native_minter.json
  tests/precompile/genesis/fee_manager.json
  tests/precompile/genesis/reward_manager.json
  tests/precompile/genesis/tx_allow_list.json
Labels: ci
