Repository ava-labs/subnet-evm, pull requests merged in 2023-09, with the labels that each got.

#840 import gomock in test templ
  accounts/abi/bind/precompilebind/precompile_bind_test.go
  accounts/abi/bind/precompilebind/precompile_config_test_template.go
Labels: testing

#838 add mock ci
  .github/workflows/auto-generated-code-checker.yml
  .github/workflows/check-clean-branch.sh
  precompile/contract/mocks.go
  scripts/mock.gen.sh
  scripts/mocks.mockgen.txt
Labels: ci

#831 x/warp: add predicate test for warp message from Primary Network
  x/warp/predicate_test.go
Labels: warp

#836 plugin/evm: Add ExampleWarp tests to vm warp unit tests
  contracts/contracts/ExampleWarp.sol
  plugin/evm/ExampleWarp.abi
  plugin/evm/ExampleWarp.bin
  plugin/evm/vm_warp_test.go
Labels: warp

#863 rename `WarpBackend` to `Backend`
  plugin/evm/network_handler.go
  plugin/evm/vm.go
  warp/backend.go
  warp/backend_test.go
  warp/handlers/signature_request.go
  warp/handlers/signature_request_test.go
  warp/warp_service.go
Labels: cleanup

#865 rename WarpClient to Client
  tests/warp/warp_test.go
  warp/warp_client.go
  warp/warp_client_fetcher.go
Labels: cleanup

#860 Bump avago rc
  .github/workflows/auto-generated-code-checker.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
  README.md
  accounts/abi/bind/bind_test.go
  accounts/abi/bind/precompilebind/precompile_bind_test.go
  go.mod
  go.sum
  peer/network_test.go
  plugin/evm/vm.go
  scripts/build.sh
  scripts/versions.sh
  tests/utils/runner/network_manager.go
  warp/backend.go
Labels: coreth-update

#859 Fix hanging requests after Shutdown (#326)
  .github/workflows/auto-generated-code-checker.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
  README.md
  accounts/abi/bind/bind_test.go
  accounts/abi/bind/precompilebind/precompile_bind_test.go
  go.mod
  go.sum
  peer/network.go
  peer/network_test.go
  plugin/evm/vm.go
  scripts/build.sh
  scripts/versions.sh
  tests/utils/runner/network_manager.go
  warp/backend.go
Labels: coreth-update

#862 Drop outbound gossip for non vdrs
  go.mod
  go.sum
  plugin/evm/vm.go
  scripts/versions.sh
Labels: coreth-update

#858 Add SDK Router message handling (#316)
  .github/workflows/auto-generated-code-checker.yml
  .github/workflows/bench.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
  README.md
  accounts/abi/bind/bind_test.go
  accounts/abi/bind/precompilebind/precompile_bind_test.go
  go.mod
  go.sum
  peer/network.go
  peer/network_test.go
  plugin/evm/vm.go
  scripts/build.sh
  scripts/versions.sh
  tests/utils/runner/network_manager.go
  warp/backend.go
Labels: coreth-update

#861 P2p sdk pull gossip
  core/txpool/txpool.go
  go.mod
  go.sum
  plugin/evm/gossip_mempool.go
  plugin/evm/gossipper_test.go
  plugin/evm/tx_gossip_test.go
  plugin/evm/vm.go
  scripts/versions.sh
Labels: coreth-update

#870 reduce duplicate code in OnSignatureRequest
  warp/handlers/signature_request.go
Labels: cleanup

#869 pass warpSigner instead of snow context into backend
  plugin/evm/vm.go
  warp/backend.go
  warp/backend_test.go
  warp/handlers/signature_request_test.go
Labels: cleanup

#881 Add Contexts Continued
  peer/client.go
  peer/network.go
  peer/network_test.go
  sync/client/client.go
  sync/client/mock_network.go
Labels: cleanup, warp

#892 Update IWarpMessenger interface name
  contracts/contracts/ExampleWarp.sol
  contracts/contracts/interfaces/IWarpMessenger.sol
Labels: warp

#888 use timer instead of time.After
  warp/aggregator/signature_getter.go
Labels: cleanup

#864 rename WarpAPI to API
  plugin/evm/vm.go
  warp/warp_client_fetcher.go
  warp/warp_service.go
Labels: cleanup

#872 verify warp is not activated before dupgrade
  precompile/testutils/test_config.go
  x/warp/config.go
  x/warp/config_test.go
Labels: warp

#900 Place stricter bounds on warp codec
  warp/payload/codec.go
Labels: warp

#891 Update preparePredicateStorageSlots doc
  core/state/statedb.go
Labels: documentation

#914 Change from parsing predicate bytes to checking they equal expected value
  plugin/evm/block.go
Labels: warp

#916 add early return
  core/predicate_check.go
Labels: warp

#918 clear messageCache on backend.Clear
  warp/backend.go
  warp/backend_test.go
Labels: bug

#883 Signature Aggregation Refactor
  plugin/evm/vm.go
  warp/aggregator/aggregation_job.go
  warp/aggregator/aggregation_job_test.go
  warp/aggregator/aggregator.go
  warp/aggregator/aggregator_test.go
  warp/aggregator/mock_signature_getter.go
  warp/aggregator/network_signature_backend.go
  warp/aggregator/signature_job.go
  warp/aggregator/signature_job_test.go
Labels: cleanup

#882 Predicate results docs
  precompile/results/README.md
Labels: documentation, warp
