Repository ava-labs/subnet-evm, pull requests merged in 2023-03, with the labels that each got.

#546 add custom marshaller for GetChainConfigResponse api
  internal/ethapi/api.go
  params/config.go
  params/config_test.go
Labels: bug

#552 Start coreth migration
  README.md
  compatibility.json
  core/blockchain.go
  core/vm/contracts.go
  go.mod
  go.sum
  peer/network.go
  plugin/evm/factory.go
  plugin/evm/version.go
  scripts/versions.sh
  sync/client/leaf_syncer.go
  sync/statesync/trie_segments.go
Labels: DO NOT MERGE

#566 Update CodeQL to v2
  .github/workflows/codeql-analysis.yml
Labels: dependencies, ci

#561 Fix Dockerfile and add Build Image to GH Actions
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Dockerfile
  scripts/build_image.sh
  scripts/constants.sh
Labels: bug

#573 Warp preparation
  accounts/abi/bind/precompilebind/precompile_module_template.go
  core/predicate_check.go
  core/predicate_check_test.go
  miner/worker.go
  params/precompile_upgrade.go
  plugin/evm/block.go
  plugin/evm/config.go
  plugin/evm/vm.go
  precompile/precompileconfig/config.go
  utils/bytes.go
  utils/bytes_test.go
  warp/backend.go
  warp/backend_test.go
  warp/handlers/signature_request.go
  warp/handlers/signature_request_test.go
  warp/warp_service.go
Labels: warp

#580 Remove unused imgs from repo
  imgs/admin_fail.png
  imgs/deploy_fail.png
  imgs/metamask_WAGMI.png
  imgs/wagmi.png
Labels: cleanup

#581 Add ignore unnecessary import to precompile contract template
  accounts/abi/bind/precompilebind/precompile_contract_template.go
Labels: bug

#589 Add ability to specify commit of avalanchego in ci
  scripts/install_avalanchego_release.sh
  scripts/versions.sh
Labels: ci
