Repository ava-labs/subnet-evm, pull requests merged in 2023-06, with the labels that each got.

#672 Fix contract examples package json
  .github/CODEOWNERS
  .github/workflows/ci.yml
  cmd/precompilegen/template-readme.md
  contracts/.gitignore
  contracts/.npmrc
  contracts/.prettierrc
  contracts/README.md
  contracts/contracts/AllowList.sol
  contracts/contracts/ERC20NativeMinter.sol
  contracts/contracts/ExampleDeployerList.sol
  contracts/contracts/ExampleFeeManager.sol
  contracts/contracts/ExampleRewardManager.sol
  contracts/contracts/ExampleTxAllowList.sol
  contracts/contracts/interfaces/IAllowList.sol
  contracts/contracts/interfaces/IFeeManager.sol
  contracts/contracts/interfaces/INativeMinter.sol
  contracts/contracts/interfaces/IRewardManager.sol
  contracts/contracts/test/AllowListTest.sol
  contracts/contracts/test/ERC20NativeMinterTest.sol
  contracts/contracts/test/ExampleDeployerListTest.sol
  contracts/contracts/test/ExampleFeeManagerTest.sol
  contracts/contracts/test/ExampleRewardManagerTest.sol
  contracts/contracts/test/ExampleTxAllowListTest.sol
  contracts/hardhat.config.ts
  contracts/index.ts
  contracts/package-lock.json
  contracts/package.json
  contracts/scripts/deployERC20NativeMinter.ts
  contracts/scripts/deployExampleDeployerList.ts
  contracts/scripts/deployExampleRewardManager.ts
  contracts/scripts/deployExampleTxAllowList.ts
  contracts/tasks.ts
  contracts/test/README.md
  contracts/test/contract_deployer_allow_list.ts
  contracts/test/contract_native_minter.ts
  contracts/test/fee_manager.ts
  contracts/test/reward_manager.ts
  contracts/test/tx_allow_list.ts
  contracts/test/utils.ts
  contracts/tsconfig.json
  tests/precompile/solidity/suites.go
  tests/utils/subnet.go
Labels: javascript, testing

#681 bump version to v0.5.2
  README.md
  compatibility.json
  go.mod
  go.sum
  plugin/evm/version.go
  scripts/versions.sh
Labels: release

#685 Remove unused ethereum-waffle and ethereumjs-tx pkgs
  contracts/package-lock.json
  contracts/package.json
Labels: javascript, cleanup

#684 move state upgrade related functions to own file
  params/precompile_upgrade.go
  params/state_upgrade.go
Labels: cleanup

#579 Update load test to use ANR for network setup
  go.mod
  go.sum
  plugin/evm/factory.go
  tests/load/load_test.go
  tests/utils/runner/network_manager.go
Labels: ci

#705 add benchmark to template
  accounts/abi/bind/precompilebind/precompile_contract_test_template.go
Labels: precompile
