Repository ava-labs/subnet-evm, pull requests merged in 2023-02, with the labels that each got.

#452 Warp backend interface and implementation
  plugin/evm/warp/backend.go
  plugin/evm/warp/backend_test.go
Labels: precompile, warp

#481 remove current rules
  plugin/evm/vm.go
Labels: cleanup

#491 parseInt from ENV var
  contract-examples/hardhat.config.ts
Labels: bug

#489 Add create precompile script to set CGO flag before running precompilegen script
  scripts/generate_precompile.sh
Labels: bug, precompile

#499 try to fix lint job
  .github/workflows/lint-tests-release.yml
Labels: ci

#498 build with avago v1.9.8
  go.mod
  go.sum
  plugin/evm/gossiper.go
  plugin/evm/warp/backend.go
  scripts/versions.sh
Labels: dependencies

#459 Signature Request Handler
  handlers/handler.go
  handlers/stats/mock_stats.go
  handlers/stats/stats.go
  handlers/warp/signature_request.go
  handlers/warp/signature_request_test.go
  handlers/warp/stats/stats.go
  plugin/evm/message/codec.go
  plugin/evm/message/handler.go
  plugin/evm/message/signature_request.go
  plugin/evm/message/signature_request_test.go
  plugin/evm/vm.go
  plugin/evm/vm_test.go
  plugin/evm/warp/backend.go
  plugin/evm/warp/backend_test.go
  sync/handlers/code_request_test.go
  sync/handlers/handler.go
Labels: precompile, warp

#492 Update codeowners
  .github/CODEOWNERS
Labels: cleanup

#507 Get signature endpoint: alternative PR with different packaging
  handlers/stats/mock_stats.go
  handlers/stats/stats.go
  plugin/evm/config.go
  plugin/evm/network_handler.go
  plugin/evm/vm.go
  warp/backend.go
  warp/backend_test.go
  warp/handlers/signature_request.go
  warp/handlers/signature_request_test.go
  warp/handlers/stats/stats.go
  warp/warp_client.go
  warp/warp_service.go
Labels: precompile, warp

#521 Update github actions to ignore rcs
  .github/workflows/lint-tests-release.yml
Labels: ci

#514 Remove unnecessary gasprice updater logic and tests
  core/tx_pool.go
  plugin/evm/block_builder_test.go
  plugin/evm/gasprice_update.go
  plugin/evm/gasprice_update_test.go
  plugin/evm/vm.go
Labels: bug, ci

#526 Bump avalanchego to v1.9.9-rc.4
  compatibility.json
  go.mod
  go.sum
  plugin/main.go
  scripts/versions.sh
  warp/backend.go
  warp/backend_test.go
  warp/handlers/signature_request_test.go
Labels: dependencies

#530 Bump AvalancheGo dep to v1.9.9
  go.mod
  go.sum
  scripts/versions.sh
Labels: dependencies

#533 Start v0.4.10 release cycle
  compatibility.json
  plugin/evm/version.go
  scripts/versions.sh
Labels: release

#542 Update compatibility in README for v0.4.10
  README.md
Labels: release
