Repository ava-labs/subnet-evm, pull requests merged in 2025-10, with the labels that each got.

#1762 chore: update avalanchego
  .github/workflows/tests.yml
  go.mod
  go.sum
Labels: dependencies, ci

#1759 sync: coreth PR #1208: feat: add TimeMilliseconds to header
  RELEASES.md
  core/chain_makers.go
  core/genesis.go
  core/genesis_extra_test.go
  core/genesis_test.go
  core/state_processor_test.go
  internal/ethapi/api.go
  internal/ethapi/testdata/eth_getBlockByHash-hash-1.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-genesis.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-latest-1-fullTx.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-latest.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-0.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-1.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-latest-1.json
  internal/ethapi/testdata/eth_getBlockByNumber-tag-latest.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-blob-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-contract-create-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-dynamic-fee-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-contract-call-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-transfer-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-tag-latest.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-0.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-1.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-latest-1.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-latest.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-0.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-1.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-latest-1.json
  internal/ethapi/testdata/eth_getHeaderByNumber-tag-latest.json
  internal/ethapi/testdata/eth_getTransactionReceipt-blob-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-with-access-list.json
  internal/ethapi/testdata/eth_getTransactionReceipt-dynamic-tx-with-logs.json
  internal/ethapi/testdata/eth_getTransactionReceipt-normal-transfer-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-with-logs.json
  miner/worker.go
  plugin/evm/customheader/time.go
  plugin/evm/customheader/time_test.go
  plugin/evm/customtypes/block_ext.go
  plugin/evm/customtypes/block_ext_test.go
  plugin/evm/customtypes/block_test.go
  plugin/evm/customtypes/gen_header_serializable_json.go
  plugin/evm/customtypes/gen_header_serializable_rlp.go
  plugin/evm/customtypes/header_ext.go
  plugin/evm/customtypes/header_ext_test.go
  plugin/evm/vm_test.go
  plugin/evm/wrapped_block.go
  rpc/subscription_test.go
Labels: coreth sync, acp226

#1758 sync: coreth PR #1044: register secp256r1 precompile
  params/hooks_libevm.go
Labels: coreth sync

#1765 sync: coreth PR #1127: feat(plugin/evm): ACP-226 - set expected block gas cost to 0 in Granite
  RELEASES.md
  core/blockchain_ext_test.go
  eth/gasprice/gasprice_test.go
  plugin/evm/customheader/block_gas_cost.go
  plugin/evm/customheader/block_gas_cost_test.go
  plugin/evm/vm_test.go
Labels: coreth sync, acp226

#1788 sync: coreth PR #1234: ACP-226: Add MinDelayExcess to header
  RELEASES.md
  core/genesis.go
  core/genesis_extra_test.go
  core/genesis_test.go
  internal/ethapi/api.go
  internal/ethapi/testdata/eth_getBlockByHash-hash-1.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-genesis.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-latest-1-fullTx.json
  internal/ethapi/testdata/eth_getBlockByHash-hash-latest.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-0.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-1.json
  internal/ethapi/testdata/eth_getBlockByNumber-number-latest-1.json
  internal/ethapi/testdata/eth_getBlockByNumber-tag-latest.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-blob-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-contract-create-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-dynamic-fee-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-contract-call-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-block-with-legacy-transfer-tx.json
  internal/ethapi/testdata/eth_getBlockReceipts-tag-latest.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-0.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-1.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-latest-1.json
  internal/ethapi/testdata/eth_getHeaderByHash-hash-latest.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-0.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-1.json
  internal/ethapi/testdata/eth_getHeaderByNumber-number-latest-1.json
  internal/ethapi/testdata/eth_getHeaderByNumber-tag-latest.json
  internal/ethapi/testdata/eth_getTransactionReceipt-blob-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-create-contract-with-access-list.json
  internal/ethapi/testdata/eth_getTransactionReceipt-dynamic-tx-with-logs.json
  internal/ethapi/testdata/eth_getTransactionReceipt-normal-transfer-tx.json
  internal/ethapi/testdata/eth_getTransactionReceipt-with-logs.json
  plugin/evm/customtypes/block_ext.go
  plugin/evm/customtypes/block_test.go
  plugin/evm/customtypes/gen_header_serializable_json.go
  plugin/evm/customtypes/gen_header_serializable_rlp.go
  plugin/evm/customtypes/header_ext.go
  plugin/evm/customtypes/header_ext_test.go
  rpc/subscription_test.go
Labels: coreth sync, acp226
