Repository ava-labs/subnet-evm, pull requests merged in 2025-09, with the labels that each got.

#1696 sync: coreth PR #958: refactor config package
  RELEASES.md
  plugin/evm/config.go
  plugin/evm/config/config.go
  plugin/evm/config/config_test.go
  plugin/evm/config/default_config.go
  plugin/evm/vm.go
  plugin/evm/vm_test.go
Labels: coreth sync

#1682 sync: coreth PR #1108: update releasing README.md with version prep instructions
  docs/releasing/README.md
Labels: docs, coreth sync

#1741 Add `TestClientWebsocketLargeMessage` flake to list of flakes
  scripts/known_flakes.txt
Labels: testing, flaky-test

#1742 sync: coreth PR: sync changes part 1: `wrapped_block.go`
  plugin/evm/block_test.go
  plugin/evm/block_verification.go
  plugin/evm/syncervm_client.go
  plugin/evm/vm.go
  plugin/evm/vm_test.go
  plugin/evm/vm_upgrade_bytes_test.go
  plugin/evm/vm_warp_test.go
  plugin/evm/wrapped_block.go
Labels: coreth sync

#1751 sync: coreth PR #1181: docs: Firewood config
  plugin/evm/config/config.md
Labels: coreth sync

#1739 Upgrade to Go 1.24
  Dockerfile
  RELEASES.md
  core/state_manager.go
  go.mod
  plugin/evm/message/block_request_test.go
  plugin/evm/message/code_request_test.go
  plugin/evm/message/leafs_request_test.go
  plugin/evm/syncervm_test.go
  sync/client/client_test.go
  sync/handlers/leafs_request_test.go
  sync/statesync/statesynctest/test_sync.go
  sync/statesync/statesynctest/test_trie.go
  sync/statesync/sync_test.go
Labels: dependencies, ci, coreth sync

#1763 Remove explicit `ethers` version set
  contracts/package-lock.json
  contracts/package.json
Labels: testing
