Repository ava-labs/subnet-evm, pull requests merged in 2025-04, with the labels that each got.

#1544 fix(cd): goreleaser picks non-rc tag and uses workflow config
  .github/workflows/release.yml
  .goreleaser.yml
Labels: PR: review needed

#1545 chore(ci): simplify monitoring configuration (re-apply #1440)
  .envrc
  .github/workflows/tests.yml
  .gitignore
  bin/tmpnetctl
  go.mod
  go.sum
  scripts/dev_shell.sh
  scripts/run_prometheus.sh
  scripts/run_promtail.sh
  scripts/update_avalanchego_version.sh
  tests/README.md
Labels: PR: review needed

#1543 update libevm branch with master branch
  .envrc
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish_antithesis_images.yml
  .github/workflows/publish_docker.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .github/workflows/trigger-antithesis.yml
  .gitignore
  .goreleaser.yml
  Dockerfile
  README.md
  bin/ginkgo
  bin/tmpnetctl
  compatibility.json
  contracts/package-lock.json
  go.mod
  go.sum
  plugin/evm/client/client.go
  plugin/evm/customrawdb/accessors_metadata_ext.go
  plugin/evm/service.md
  plugin/evm/version.go
  precompile/allowlist/allowlist.go
  precompile/contracts/rewardmanager/contract.go
  precompile/contracts/warp/README.md
  scripts/actionlint.sh
  scripts/dev_shell.sh
  scripts/run_ginkgo_load.sh
  scripts/run_ginkgo_precompile.sh
  scripts/run_ginkgo_warp.sh
  scripts/run_prometheus.sh
  scripts/run_promtail.sh
  scripts/update_avalanchego_version.sh
  scripts/versions.sh
  sync/statesync/code_syncer.go
  tests/README.md
  utils/metered_cache.go
Labels: PR: review needed, libevm

#1551 fix(all): critical fixes to the libevm branch
  core/genesis.go
  core/genesis_extra_test.go
  params/extras/config.go
  params/extras/config_test.go
  params/extras/precompile_config_test.go
  params/extras/precompile_upgrade_test.go
Labels: PR: review needed, libevm

#1511 docs(readme): add release badge
  README.md
Labels: docs, PR: review needed

#1444 docs(readme): add license badge
  README.md
Labels: docs
